version: 1.0.{build}
image: Visual Studio 2015

environment:
  QT5DIR: C:\Qt\5.8

install:
  - cmd: SET CMAKE_PREFIX_PATH=%QT5DIR%\msvc2015_64

build_script:
  - cmd: cmake -G "Visual Studio 14 2015 Win64"  -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=On
  - cmd: cmake --build . --target install --config Release -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cmd: C:\Qt\5.8\msvc2015_64\bin\windeployqt.exe Exec/KVEngine.exe
  - cmd: ren Exec Griefly

test_script:
  - cmd: cd Griefly
  - cmd: KVEngine.exe --run-tests

artifacts:
  - path: Griefly
    name: Griefly
