version: 1.0.{build}
image: Visual Studio 2015

environment:
  QT5DIR: C:\Qt\5.8

install:
  - cmd: SET CMAKE_PREFIX_PATH=%QT5DIR%\msvc2015_64

build_script:
  - cmd: cmake -G "NMake Makefiles" -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=On
  - cmd: cmake --build . --target install --config Release -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  # For tests
  - cmd: set PATH=%QT5DIR%/msvc2015_64/bin/;%PATH%
  - cmd: set PATH=%QT5DIR%/msvc2015_64/plugins/;%PATH%

test_script:
  - cmd: cd Exec
  - cmd: KVEngine.exe --run-tests
